# Generated by Django 4.0.2 on 2022-03-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_price_to_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='Zip',
            field=models.CharField(default='-', max_length=225),
            preserve_default=False,
        ),
    ]
